
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear a binding back to UNBOUND (empty `current_binding`).
 * 
 * `change_binding` deliberately rejects an empty value — every *normal*
 * shortcut must always hold one. But bindings seeded unbound (a meeting-capture
 * hotkey, per-agent hotkeys) have "unset" as a legitimate state the user can
 * return to. This unregisters the live shortcut and persists the empty value
 * without going through `change_binding`, so transcribe/cancel are untouched.
 */
async clearBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable the hands-free wake-word listener. Persists the setting and
 * starts/stops the background [`WakeWordManager`] loop to match.
 */
async setHandsFreeEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hands_free_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable spoken hands-free acknowledgment cues ("Got it" / "Now
 * typing"). Persists the setting; the running listener reads it per segment, so
 * no restart is needed.
 */
async setHandsFreeVoiceFeedback(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hands_free_voice_feedback", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the wake phrase the listener matches (rejects an empty value).
 */
async setWakeWord(wakeWord: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word", { wakeWord }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the fuzzy wake-word match threshold (clamped to 0.0..=1.0).
 */
async setWakeWordSensitivity(value: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_sensitivity", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-speech grace window (seconds): after the wake word, how long to wait for
 * the user to START speaking before giving up. Clamped to 3..=120. Once they
 * speak, capture extends while speech continues and ends on the silence timeout,
 * so a short command isn't forced to wait out this whole window.
 */
async setWakeWordListenSeconds(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_listen_seconds", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * How long (seconds) of continuous silence ends the command capture once the
 * user has started speaking. Clamped to 1..=15s. This is the "smart" part: the
 * mic stays open as long as speech keeps arriving and stops shortly after the
 * user finishes.
 */
async setWakeWordSilenceTimeoutSeconds(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_silence_timeout_seconds", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report whether hands-free wake-word detection can actually run: it needs the
 * selected local STT model present on disk. Reuses [`ModelManager`]'s existing
 * on-disk `is_downloaded` view rather than probing files here.
 */
async getHandsFreeReadiness() : Promise<Result<HandsFreeReadiness, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hands_free_readiness") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAdvancedModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_advanced_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDictionary(entries: DictionaryEntry[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary", { entries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set (or, with an empty prompt, remove) the per-app cleanup prompt override
 * for a given active-app name. See `AppSettings::per_app_prompts`.
 */
async setPerAppPrompt(appName: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_per_app_prompt", { appName, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return all configured per-app cleanup prompt overrides.
 */
async getPerAppPrompts() : Promise<Result<Partial<{ [key in string]: string }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_per_app_prompts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSttBackendMode(mode: SttBackendMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_stt_backend_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSttProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_stt_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSttModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_stt_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSttSelfhostedUrlSetting(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_stt_selfhosted_url_setting", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSttSelfhostedModelSetting(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_stt_selfhosted_model_setting", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSttSelfhostedApiStyle(style: SttApiStyle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_stt_selfhosted_api_style", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store an API key in the OS keychain. `scope` is "stt" or "cleanup",
 * `provider` is the provider id (e.g. "groq"). Empty key deletes the entry.
 */
async setApiKey(scope: string, provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key", { scope, provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a key exists for (scope, provider). We never return the key itself.
 */
async hasApiKey(scope: string, provider: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_api_key", { scope, provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteApiKey(scope: string, provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key", { scope, provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List models for an OpenAI-compatible STT endpoint (self-hosted or a provider
 * with a `/models` endpoint). Deepgram has no such endpoint → returns a curated
 * static list.
 */
async listSttModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stt_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record ~2 s from the mic and transcribe it through the *currently selected*
 * STT backend, returning the text + measured latency. Powers the STT card's
 * "Test" button.
 */
async testSttBackend() : Promise<Result<BackendTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_stt_backend") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a fixed noisy sample through the *currently selected* cleanup backend and
 * return the polished text + latency. Powers the Cleanup card's "Test" button.
 */
async testCleanupBackend() : Promise<Result<BackendTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_cleanup_backend") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAgent(agent: AgentDefinition) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_agent", { agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAgent(agent: AgentDefinition) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent", { agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAgent(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the agent's persona LLM over `sample_text` and return the output +
 * latency. Powers the agent card's "Test" button (mirrors `test_cleanup_backend`).
 */
async testAgent(id: string, sampleText: string) : Promise<Result<AgentTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_agent", { id, sampleText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAiMode(mode: AiMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_ai_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAiMode(mode: AiMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ai_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAiMode(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_ai_mode", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the mode's transform over `sample_text` and return the output + latency.
 * Powers the mode card's "Test" button (mirrors `test_agent`). For `Direct`
 * modes this returns the sample text unchanged (no LLM call).
 */
async testAiMode(id: string, sampleText: string) : Promise<Result<AiModeTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_ai_mode", { id, sampleText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List currently-running apps for the mode card's "Activate when using" picker.
 * Best-effort — an empty list just means the user types bundle ids / names by
 * hand.
 */
async getRunningApps() : Promise<RunningApp[]> {
    return await TAURI_INVOKE("get_running_apps");
},
/**
 * Set the default AI Mode applied on the main hotkey when post-processing is on.
 * `None` (or an empty/whitespace string) = the built-in **Write** mode = today's
 * cleanup path. `Some(id)` must reference an existing mode; unknown/disabled ids
 * are accepted (stored) but degrade to Write at resolution time.
 */
async setDefaultAiModeId(modeId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_ai_mode_id", { modeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the light, NON-AI basic filler filter (um/uh/… on Raw/Direct only).
 */
async setBasicFillerFilter(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_basic_filler_filter", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the hotkey cheat-sheet overlay master switch (D2). The `hotkey_overlay`
 * binding ships unbound, so this only matters once the user assigns a hotkey.
 */
async setHotkeyOverlayEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hotkey_overlay_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a CLI agent's binary path by looking up its canonical name on PATH
 * (`which`-style). Returns the absolute path, or an error if not found. The
 * PATH searched is the baseline-augmented one (Homebrew etc.), matching how the
 * run will actually be spawned.
 */
async detectAgentBinary(cliType: AgentCliType) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_agent_binary", { cliType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the prefilled `command_template` / `prompt_via` / binary name for a
 * CLI type. The frontend calls this when the user picks an agent type.
 */
async getCliAgentDefaults(cliType: AgentCliType) : Promise<CliAgentDefaults> {
    return await TAURI_INVOKE("get_cli_agent_defaults", { cliType });
},
/**
 * Run `<binary> --version` (best-effort) and report success + captured output.
 * Never fails the command itself on a non-zero exit — the caller inspects `ok`.
 */
async testAgentBinary(binaryPath: string) : Promise<Result<AgentBinaryTest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_agent_binary", { binaryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot of all CLI agent runs (running + recent), newest first.
 */
async listAgentRuns() : Promise<AgentRunInfo[]> {
    return await TAURI_INVOKE("list_agent_runs");
},
/**
 * Request a stop (SIGTERM→SIGKILL) for a running CLI agent run.
 */
async stopAgentRun(runId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop all terminal (finished/failed/stopped) runs from the registry.
 */
async clearFinishedAgentRuns() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_finished_agent_runs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalyticsSummary(rangeDays: number | null) : Promise<Result<AnalyticsSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analytics_summary", { rangeDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDictationsOverTime(rangeDays: number | null) : Promise<Result<OverTimePoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictations_over_time", { rangeDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalyticsByApp(rangeDays: number | null) : Promise<Result<AppUsage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analytics_by_app", { rangeDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalyticsByProject(rangeDays: number | null) : Promise<Result<ProjectUsage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analytics_by_project", { rangeDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTopKeywords(rangeDays: number | null, limit: number | null) : Promise<Result<KeywordCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_top_keywords", { rangeDays, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAnalyticsPrivacy(mode: AnalyticsPrivacy) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_analytics_privacy", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAnalytics() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_analytics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start capturing a meeting. `app_bundle_id` (when known) targets the system
 * audio tap at that app's PID; capture degrades to mic-only on any tap failure.
 */
async startMeetingCapture(appBundleId: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting_capture", { appBundleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the active meeting capture and finalize it.
 */
async stopMeetingCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a capture is running (and whether system audio degraded to mic-only).
 */
async getMeetingCaptureStatus() : Promise<Result<MeetingCaptureStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_capture_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All meetings, newest first.
 */
async listMeetings() : Promise<Result<MeetingSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A single meeting with its transcript segments.
 */
async getMeeting(meetingId: number) : Promise<Result<MeetingDetail | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting, its segments, and its WAVs.
 */
async deleteMeeting(meetingId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the meetings feature master switch.
 */
async setMeetingsEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meetings_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle meeting auto-detection (the record prompt). Capture start stays
 * user-confirmed regardless.
 */
async setMeetingAutoDetect(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meeting_auto_detect", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a per-meeting speaker cluster ("Speaker 1" → "Alice"). An empty name
 * clears the custom label back to the default. Scoped to this meeting only.
 */
async renameMeetingSpeaker(meetingId: number, localSpeaker: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting_speaker", { meetingId, localSpeaker, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The per-meeting speaker display names.
 */
async getMeetingSpeakers(meetingId: number) : Promise<Result<MeetingSpeakerRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_speakers", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diarization availability + effective mode (for the status chip + settings).
 */
async getDiarizationStatus() : Promise<Result<DiarizationStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diarization_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the diarization master switch. Enabling it does NOT download models —
 * the frontend calls `download_diarization_models` explicitly so the ~34 MB
 * fetch is always a deliberate, progress-tracked action.
 */
async setMeetingsDiarization(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meetings_diarization", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle live provisional labels (opt-in; off by default on slow machines).
 */
async setMeetingsDiarizationProvisional(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meetings_diarization_provisional", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiarizationModelsStatus() : Promise<Result<DiarizationModelsStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diarization_models_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download + verify the diarization models (progress via
 * `diarization-model-progress`). Only ever called on explicit user action.
 */
async downloadDiarizationModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_diarization_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
agentRunOutput: AgentRunOutput,
agentRunStatus: AgentRunStatus,
historyUpdatePayload: HistoryUpdatePayload,
meetingDetected: MeetingDetected,
meetingLevels: MeetingLevels,
meetingSegmentEvent: MeetingSegmentEvent,
meetingSpeakersUpdated: MeetingSpeakersUpdated,
meetingState: MeetingState,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
agentRunOutput: "agent-run-output",
agentRunStatus: "agent-run-status",
historyUpdatePayload: "history-update-payload",
meetingDetected: "meeting-detected",
meetingLevels: "meeting-levels",
meetingSegmentEvent: "meeting-segment-event",
meetingSpeakersUpdated: "meeting-speakers-updated",
meetingState: "meeting-state",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Result of `test_agent_binary`: whether the binary ran and its version output.
 */
export type AgentBinaryTest = { ok: boolean; output: string; hint: AgentBinaryHint | null }
/**
 * Classified, actionable failure modes surfaced by `test_agent_binary`. The
 * frontend renders a localized fix for each instead of a raw spawn stack.
 */
export type AgentBinaryHint = "codex_vendor_missing"
/**
 * Which local coding-agent CLI a `Cli` agent drives. Selects the prefilled
 * invocation template (see `default_command_template_for`). `Custom` is a
 * fully user-defined template for any other binary.
 */
export type AgentCliType = "claude" | "codex" | "openclaw" | "hermes" | "custom"
/**
 * A Flow OS agent: dictation routed through a persona LLM before injection.
 * Each agent has its own global hotkey (via a seeded `ShortcutBinding` keyed
 * `agent:<id>`). All optional fields are `#[serde(default)]` so an old settings
 * store (with no `agents` key, or partial entries) always deserializes cleanly —
 * the store wipes to defaults on any parse failure.
 */
export type AgentDefinition = { 
/**
 * Stable slug, e.g. "coder"; unique. Matches `^[a-z0-9_-]{1,48}$`.
 */
id: string; 
/**
 * Display name shown in the UI.
 */
name: string; enabled?: boolean; 
/**
 * ALWAYS `"agent:<id>"` — the join key into `AppSettings.bindings`.
 */
binding_id: string; 
/**
 * References an existing `post_process_providers` entry.
 */
provider_id: string; model?: string; 
/**
 * The persona used as the LLM system prompt.
 */
system_prompt?: string; output_mode?: AgentOutputMode; 
/**
 * Discriminator. `Prompt` (default) → increment-1 persona-LLM behavior,
 * unchanged. `Cli` → drive a real coding-agent subprocess (fields below).
 */
kind?: AgentKind; 
/**
 * Which coding CLI this agent drives (only meaningful when `kind == Cli`).
 */
cli_type?: AgentCliType | null; 
/**
 * Resolved/overridable path to the agent binary (e.g. `/usr/local/bin/claude`).
 */
binary_path?: string; 
/**
 * Argv template appended after the binary; supports `{cwd}`/`{prompt}`
 * placeholders (see `AgentRunManager::build_argv`). Prefilled per `cli_type`.
 */
command_template?: string; 
/**
 * Project folder the agent runs in (`cwd`). `""` = no fixed project (a
 * sensible default dir is used at run time).
 */
project_path?: string; 
/**
 * Where run output goes. Defaults to `[Panel]` (live in-app stream only).
 */
output_sinks?: AgentOutputSink[]; 
/**
 * How the instruction reaches the CLI. `Stdin` (default) or `Arg`.
 */
prompt_via?: PromptDelivery }
/**
 * Flow OS increment 2 — what KIND of agent this is. `Prompt` is the increment-1
 * behavior (dictation routed through a persona LLM before injection). `Cli`
 * drives a REAL local coding-agent binary (Claude Code, Codex, …) as a
 * subprocess in a chosen project folder. Defaults to `Prompt` so every agent
 * stored before this field existed stays a prompt agent, byte-for-byte.
 */
export type AgentKind = "prompt" | "cli"
/**
 * What an agent does with its LLM response. `Inject` pastes it at the cursor
 * exactly like a normal dictation; `Clipboard` only copies it (no paste, no
 * auto-submit) and shows a brief confirmation. Defaults to `Inject`.
 */
export type AgentOutputMode = "inject" | "clipboard"
/**
 * Where a CLI agent run's output goes (multi-select). `Panel` is the live
 * streamed in-app view (always effectively on for a running view). `Notify`
 * fires a desktop notification on completion. `File` writes the full
 * instruction+output to a markdown file in the project.
 */
export type AgentOutputSink = "panel" | "notify" | "file"
/**
 * A snapshot of a run for the frontend (`list_agent_runs`).
 */
export type AgentRunInfo = { run_id: string; agent_id: string; agent_name: string; project_path: string; status: RunStatus; 
/**
 * RFC3339 local start time (for display).
 */
started_at: string; 
/**
 * Epoch milliseconds — for stable sorting and elapsed-time computation.
 */
started_at_ms: number; 
/**
 * Rolling (capped) combined stdout+stderr buffer.
 */
output: string; 
/**
 * The instruction (transcript) that drove the run.
 */
instruction: string; 
/**
 * Absolute path to the written run file, once the File sink has run.
 */
output_file: string | null }
/**
 * Emitted per output line while a run streams. Event name: `agent-run-output`.
 */
export type AgentRunOutput = { run_id: string; chunk: string }
/**
 * Emitted when a run reaches a terminal status. Event name: `agent-run-status`.
 */
export type AgentRunStatus = { run_id: string; status: RunStatus }
/**
 * Result of the agent "Test" action: the LLM's output plus how long it took.
 * Mirrors `BackendTestResult` / `test_cleanup_backend`.
 */
export type AgentTestResult = { output: string; latency_ms: number }
/**
 * A user-defined **AI Mode**: a named dictation profile with its own optional
 * global hotkey and optional per-app auto-selection rules. Modes generalize the
 * built-in cleanup ("Write") path — see [`AiModeKind`]. Every field beyond
 * `id`/`name`/`binding_id` is `#[serde(default)]` so an old settings store (no
 * `ai_modes` key, or partial entries) always deserializes cleanly; with
 * `ai_modes` empty the app behaves byte-for-byte as before this field existed.
 */
export type AiMode = { 
/**
 * Stable slug, e.g. "translate"; unique. Matches `^[a-z0-9_-]{1,48}$`.
 */
id: string; 
/**
 * Display name shown in the UI.
 */
name: string; 
/**
 * What this mode does to the transcript. Defaults to `Rewrite`.
 */
kind?: AiModeKind; enabled?: boolean; 
/**
 * ALWAYS `"mode:<id>"` — the join key into `AppSettings.bindings`.
 */
binding_id: string; 
/**
 * The editable prompt *body* (tone/instructions). Appended to a fixed hidden
 * base prompt at call time; empty for `Direct`.
 */
prompt?: string; 
/**
 * Optional provider override. `None`/empty → inherit the active cleanup
 * provider (`active_post_process_provider`).
 */
provider_id?: string | null; 
/**
 * Optional model override. `None`/empty → inherit the provider's configured
 * cleanup model (`post_process_models[provider_id]`).
 */
model?: string | null; 
/**
 * Bundle-id or app-name substrings for per-app auto-selection on the MAIN
 * hotkey. Empty → this mode is never auto-selected (hotkey-only). Matching is
 * case-insensitive substring both directions against the frontmost app's
 * bundle id AND localized name (same semantics as `per_app_prompts`).
 */
app_rules?: string[] }
/**
 * What an AI Mode does with the raw transcript before it reaches the cursor.
 * 
 * - `Rewrite` (default): route the transcript through a cleanup-style LLM using
 * the mode's editable prompt as the tone/instruction body (on top of a fixed,
 * hidden base prompt). This generalizes the existing post-process cleanup.
 * - `Command`: ask the LLM to translate the spoken request into a single bare
 * shell command via structured output, then TYPE it at the cursor. It is
 * NEVER executed and auto-submit is force-disabled for the injection.
 * - `Direct`: inject the raw transcript verbatim, skipping the LLM entirely.
 * 
 * Defaults to `Rewrite` so any partial/older stored mode deserializes as a
 * plain rewrite mode.
 */
export type AiModeKind = "rewrite" | "command" | "direct"
/**
 * Result of the AI mode "Test" action: the transformed output plus how long it
 * took. Mirrors `AgentTestResult` / `test_agent`.
 */
export type AiModeTestResult = { output: string; latency_ms: number }
/**
 * The wire protocol an HTTP STT endpoint speaks. Most providers and
 * self-hosted servers (OpenAI, Groq, Speaches, whisper-server, LocalAI) use the
 * OpenAI `/audio/transcriptions` multipart shape; Deepgram is different enough
 * to need its own adapter.
 * How much of each dictation the analytics backend persists. `Full` stores
 * everything; `KeywordsOnly` keeps derived keywords but nulls raw/cleaned text
 * and window titles; `Off` skips logging entirely.
 */
export type AnalyticsPrivacy = "full" | "keywords_only" | "off"
export type AnalyticsSummary = { total_dictations: number; total_words: number; avg_wpm: number; time_saved_seconds: number; current_streak_days: number; active_apps_count: number }
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes — see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; 
/**
 * Basic vs. Advanced UI mode. When false (default), the settings sidebar
 * shows only the core speech-to-text sections; when true, every section is
 * revealed. Purely a UI gate — it never disables any underlying feature.
 */
advanced_mode?: boolean; log_level?: LogLevel; 
/**
 * Legacy flat custom-word list. Kept deserializable for back-compat and
 * migrated into `dictionary` on load; `dictionary` is the source of truth.
 */
custom_words?: string[]; 
/**
 * User dictionary: canonical spellings + "sounds like" alias rules.
 */
dictionary?: DictionaryEntry[]; 
/**
 * One-shot marker for the legacy `custom_words` → `dictionary` migration
 * (see `apply_settings_migrations`). Missing/`false` means the migration
 * hasn't run yet; once it runs (whether or not there was anything to
 * migrate) this is set `true` forever, so a user who later deletes every
 * dictionary entry doesn't get `custom_words` silently re-migrated back in
 * on the next settings read. Fresh installs start `true` since there is
 * nothing to migrate.
 */
dictionary_migrated?: boolean; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; 
/**
 * Per-app cleanup prompt overrides: active-app name (as returned by
 * `active_app::current().app_name`, e.g. "Slack", "Visual Studio Code",
 * "Mail") → a cleanup prompt/instruction string. When the frontmost app
 * matches an entry, its prompt is used instead of the selected default.
 */
per_app_prompts?: Partial<{ [key in string]: string }>; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; transcribe_gpu_device?: number; extra_recording_buffer_ms?: number; vad_enabled?: boolean; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this — that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle; 
/**
 * Where STT runs: on-device (`Local`), a user-typed endpoint (`SelfHosted`),
 * or a named cloud provider (`Remote`). Independent of the cleanup backend.
 */
stt_backend_mode?: SttBackendMode; 
/**
 * Selected remote provider id (indexes `stt_providers`).
 */
stt_provider_id?: string; stt_providers?: SttProvider[]; 
/**
 * Per-provider chosen model name (provider id → model).
 */
stt_models?: Partial<{ [key in string]: string }>; 
/**
 * Self-hosted (Mode B) endpoint URL, e.g. a Speaches / whisper-server base.
 */
stt_selfhosted_url?: string; stt_selfhosted_model?: string; stt_selfhosted_api_style?: SttApiStyle; 
/**
 * How much of each dictation the usage-analytics backend persists.
 */
analytics_privacy?: AnalyticsPrivacy; 
/**
 * Master switch for the always-on wake-word listener. When true, the
 * `WakeWordManager` runs a background loop that listens for the wake phrase
 * and starts a voice-triggered dictation (no hotkey required).
 */
hands_free_enabled?: boolean; 
/**
 * The wake phrase the listener matches at the start of an utterance.
 */
wake_word?: string; 
/**
 * Similarity threshold (0.0..=1.0) for the fuzzy wake-word match. Higher is
 * stricter; the default is a good balance for the "hey flow" default phrase.
 */
wake_word_sensitivity?: number; 
/**
 * Pre-speech grace window (seconds): after the wake word, how long to wait
 * for the user to START speaking before giving up. A pause after the wake
 * word (while gathering a thought) never cuts them off. Once they DO speak,
 * capture keeps extending while speech continues and ends shortly after they
 * go quiet (see `wake_word_silence_timeout_ms`) — so a short command submits
 * promptly rather than waiting out this whole window.
 */
wake_word_listen_seconds?: number; 
/**
 * Once the minimum window has elapsed AND the user has spoken, how long
 * (milliseconds) of continuous silence ends the command capture. This is what
 * makes hands-free "smart": short commands finish quickly, long ones keep the
 * mic open as long as speech continues. Clamped to a sane range at the command.
 */
wake_word_silence_timeout_ms?: number; 
/**
 * When true, hands-free plays short spoken acknowledgment cues: "Got it"
 * after a wake match (before the command mic opens) and "Now typing" just
 * before the transcribed text is injected. Reuses the audio-feedback volume
 * and selected output device. Default on.
 */
hands_free_voice_feedback?: boolean; 
/**
 * User-defined agents. Empty by default. Purely additive — an old store
 * with no `agents` key deserializes to an empty list, so behavior with no
 * agents configured is byte-for-byte identical to before this field existed.
 */
agents?: AgentDefinition[]; 
/**
 * User-defined AI Modes. Empty by default. Purely additive — an old store
 * with no `ai_modes` key deserializes to an empty list, so behavior with no
 * modes configured is byte-for-byte identical to before this field existed.
 * The built-in cleanup ("Write") path is NOT stored here; it remains the
 * existing `post_process_*` settings and is only *presented* as a mode.
 */
ai_modes?: AiMode[]; 
/**
 * The default AI Mode applied on the MAIN hotkey when post-processing is on
 * and no higher-precedence source (hotkey mode / app-rule mode / legacy
 * per-app prompt) matched. `None` = the built-in **Write** mode = today's
 * exact cleanup path (byte-for-byte unchanged). `Some(id)` points at an
 * enabled `ai_modes` entry that replaces the cleanup pass. Additive &
 * serde-defaulted: an old store deserializes to `None` → no behavior change.
 */
default_ai_mode_id?: string | null; 
/**
 * Light, NON-AI filler filter. When `true`, standalone latin-script fillers
 * (um/uh/uhm/erm/hmm variants) are stripped from the injected text — but ONLY
 * for utterances that resolve to Raw (post-processing off) or a `Direct`
 * mode, never when an LLM cleanup/rewrite already runs. Default `false` = no
 * behavior change. See `audio_toolkit::text::strip_basic_fillers`.
 */
basic_filler_filter?: boolean; 
/**
 * Master switch for the "Show hotkeys" cheat-sheet overlay. Default `true` is
 * safe because the `hotkey_overlay` binding ships UNBOUND — there is zero
 * behavior until the user assigns it a hotkey. When bound, holding the hotkey
 * shows a panel of every configured shortcut.
 */
hotkey_overlay_enabled?: boolean; 
/**
 * Master switch for the meetings feature (capture + on-device transcription).
 * Additive & fully defaultable; when false the detector never runs and manual
 * capture is refused. Default on so the shipped feature is usable.
 */
meetings_enabled?: boolean; 
/**
 * Auto-detect meetings (known bundle id + mic-in-use fusion) and offer to
 * capture. Default on; capture start is always user-confirmed regardless.
 */
meeting_auto_detect?: boolean; 
/**
 * Bundle ids treated as meeting apps for auto-detection. User-extensible
 * (Webex/Slack huddles etc.); defaults to Zoom, Teams (classic + new), FaceTime.
 */
meeting_app_allowlist?: string[]; 
/**
 * Master switch for on-device speaker diarization. Default on: when the
 * models are absent nothing downloads and meetings behave exactly like M1
 * (segments stay "Them"), so on-by-default is safe. Enabling it in the UI is
 * what triggers the one-time model download — never at startup.
 */
meetings_diarization?: boolean; 
/**
 * Run *live provisional* labels (re-diarize every ~30 s) in addition to the
 * canonical final pass. Default **off**: the Intel benchmark (~0.14× realtime
 * on the i9-9980HK) makes full-accumulated re-diarization every 30 s
 * infeasible past a few minutes, so the safe default is final-pass-only
 * (DESIGN-meetings.md §5.4 auto-degrade). Users on fast machines can opt in.
 */
meetings_diarization_provisional?: boolean }
export type AppUsage = { app: string; dictations: number; words: number }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
/**
 * Result of a `Test` action (STT or cleanup): what came back and how long it
 * took, so the setup UI can show "it works, ~740 ms" before the user commits.
 */
export type BackendTestResult = { ok: boolean; message: string; 
/**
 * Transcribed / cleaned sample text (empty on failure).
 */
text: string; latency_ms: number; 
/**
 * The backend that actually ran, e.g. "remote:groq" or "local".
 */
backend: string }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * The prefilled config for a CLI agent type — one source of truth shared with
 * the frontend so its "Add CLI agent" form matches exactly what the backend
 * verified (esp. the live-tested `claude` template).
 */
export type CliAgentDefaults = { command_template: string; prompt_via: PromptDelivery; 
/**
 * Canonical binary name to auto-detect on PATH (`None` for `custom`).
 */
binary_name: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
/**
 * Which diarization mode a meeting will run, after the degrade decision.
 */
export type DiarizationMode = 
/**
 * Live provisional labels (~30 s re-diarization) plus the final pass.
 */
"provisional" | 
/**
 * One canonical pass at meeting end only (the Intel-safe default).
 */
"final_only" | 
/**
 * Diarization disabled or models missing — segments stay "Them" (M1).
 */
"off"
/**
 * Whether the diarization models are installed + their total download size.
 */
export type DiarizationModelsStatus = { installed: boolean; size_mb: number }
/**
 * Diarization availability + the mode a meeting would run in, for the settings
 * card and the transcript status chip.
 */
export type DiarizationStatus = { 
/**
 * The `meetings_diarization` setting.
 */
enabled: boolean; 
/**
 * Whether both diarization models are on disk.
 */
models_installed: boolean; 
/**
 * The `meetings_diarization_provisional` opt-in.
 */
provisional: boolean; 
/**
 * Effective mode (`provisional` | `final_only` | `off`).
 */
mode: DiarizationMode }
/**
 * A user dictionary entry: a canonical spelling plus optional "sounds like"
 * aliases (misheard/alternate forms) that are rewritten to the canonical word.
 * Supersedes the flat `custom_words` list (legacy entries migrate to one entry
 * each with no aliases). See `audio_toolkit::text::apply_dictionary`.
 */
export type DictionaryEntry = { 
/**
 * Canonical spelling used in the output. Spaces are allowed (phrases).
 */
word: string; 
/**
 * Aliases / misheard forms that are replaced by `word`. Matched exactly
 * first (deterministic, threshold-independent) then fuzzily.
 */
sounds_like?: string[]; 
/**
 * When true, only deterministic alias replacement runs for this entry — the
 * fuzzy pass never matches against `word` (or its aliases).
 */
replace_exact?: boolean; 
/**
 * When true, `word`'s exact casing is emitted verbatim (bypasses the
 * case-pattern preservation that otherwise mirrors the input token's case).
 */
case_sensitive?: boolean }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type GpuDeviceOption = { id: number; name: string; total_vram_mb: number }
/**
 * Readiness of the hands-free wake-word listener: whether the currently selected
 * local STT model is downloaded on disk. Wake-word *detection* always needs a
 * local model, even for users who dictate via a remote STT backend, so the UI
 * warns when it's missing (detection — and therefore dictation — can't work).
 */
export type HandsFreeReadiness = { 
/**
 * Whether the selected model exists on disk and can drive detection.
 */
local_model_available: boolean; 
/**
 * The currently selected model id, or `None` if nothing is selected.
 */
selected_model: string | null }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type KeywordCount = { keyword: string; count: number }
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Snapshot for the frontend: is a capture running, and did system audio degrade?
 */
export type MeetingCaptureStatus = { active: boolean; meeting_id: number | null; mic_only: boolean; notice?: string | null }
export type MeetingDetail = { meeting: MeetingRecord; segments: MeetingSegmentRecord[]; 
/**
 * Per-meeting speaker display names (M2 rename). Empty when none set.
 */
speakers?: MeetingSpeakerRecord[] }
/**
 * A known meeting app is running and the mic is in use — offer to capture.
 * Emitted by the [`crate::meeting::detector`].
 */
export type MeetingDetected = { bundle_id: string; app_name: string }
/**
 * Two-channel input levels (0.0..~1.0 RMS) for the live meters.
 */
export type MeetingLevels = { mic: number; system: number }
export type MeetingRecord = { id: number; started_at: number; ended_at: number | null; title: string; app_bundle_id: string | null; status: string; mic_wav: string | null; system_wav: string | null; diarized: boolean }
/**
 * A freshly transcribed turn appended to the live transcript.
 */
export type MeetingSegmentEvent = { meeting_id: number; segment: MeetingSegmentRecord }
export type MeetingSegmentRecord = { id: number; meeting_id: number; t_start_ms: number; t_end_ms: number; 
/**
 * `mic` ("You") or `system` ("Them").
 */
channel: string; 
/**
 * Per-meeting diarization cluster (M2); `None` in M1.
 */
local_speaker: number | null; 
/**
 * Voice-fingerprint registry match (M3); `None` in M1.
 */
speaker_id: number | null; text: string; 
/**
 * Bit flags — bit 0 = private (spoken to OpenFlow during the meeting).
 */
flags?: number }
/**
 * A per-meeting speaker display name ("Speaker 1" renamed to "Alice"), scoped to
 * one meeting. Does not touch the M3 fingerprint registry.
 */
export type MeetingSpeakerRecord = { local_speaker: number; name: string }
/**
 * Diarization relabeled a meeting's remote segments (after a provisional cycle
 * or the canonical final pass). The UI re-renders past segments with the new
 * `local_speaker` labels. `final_pass` marks the canonical result.
 */
export type MeetingSpeakersUpdated = { meeting_id: number; 
/**
 * Distinct per-meeting speaker ordinals present after relabeling.
 */
speakers: number[]; final_pass: boolean }
/**
 * Meeting session status transition (`recording` | `processing` | `done` |
 * `failed`). `mic_only` / `notice` communicate a graceful system-audio degrade.
 */
export type MeetingState = { meeting_id: number; status: string; mic_only?: boolean; 
/**
 * Stable machine tag for the degrade notice (`unsupported` | `permission` |
 * `no_audio` | `mic_only` | `error`), or `None` when both channels captured.
 */
notice?: string | null }
export type MeetingSummary = { id: number; started_at: number; ended_at: number | null; title: string; app_bundle_id: string | null; status: string; segment_count: number; 
/**
 * Milliseconds from the first to the last segment (0 while empty).
 */
duration_ms: number }
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how OpenFlow obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverTimePoint = { date: string; dictations: number; words: number }
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type ProjectUsage = { project: string; dictations: number; words: number }
/**
 * How a CLI agent receives the instruction (transcript). `Stdin` (default)
 * writes it to the process stdin — no OS arg-length limit, mirroring Agent OS.
 * `Arg` substitutes it into the `{prompt}` placeholder in the command template.
 */
export type PromptDelivery = "stdin" | "arg"
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * Terminal/live status of a run. Internally tagged so the TS side is a clean
 * discriminated union: `{ status: "running" } | { status: "finished", code }`
 * | `{ status: "failed", error }` | `{ status: "stopped" }`.
 */
export type RunStatus = { status: "running" } | { status: "finished"; code: number } | { status: "failed"; error: string } | { status: "stopped" }
/**
 * A currently-running application with a bundle id and localized name. Used by
 * the AI Mode "Activate when using" app-rules picker.
 */
export type RunningApp = { bundle_id: string; name: string }
export type SecretMap = Partial<{ [key in string]: string }>
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing — show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
export type SttApiStyle = "openai_compatible" | "deepgram"
/**
 * Where speech-to-text runs. `Local` uses the bundled on-device engine
 * (OpenFlow's Parakeet/Whisper). `SelfHosted` and `Remote` both POST audio to an
 * HTTP endpoint — the only difference is UX (a user-typed URL vs. a named
 * provider) and where the key comes from.
 */
export type SttBackendMode = "local" | "self_hosted" | "remote"
/**
 * A remote STT provider entry (Mode C) or the template for a self-hosted one.
 */
export type SttProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; api_style?: SttApiStyle; default_model?: string; 
/**
 * Optional `/models` listing endpoint (OpenAI-compatible only).
 */
models_endpoint?: string | null }
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
